# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

mail_from_address: ''
address: ''
port: ''
domain: ''
authentication: 'plain'
enable_starttls_auto: 'true'
user_name: ''
password: ''
ssl: 'true'
tls: 'true'

development:
  mail_from_address: 'ruby.rails@inbox.ru'
  address: 'smtp.mail.ru'
  port: '465'
  domain: 'mail.ru'
  authentication: 'plain'
  user_name: 'ruby.rails@inbox.ru'
  password: 'qwe123asd'

production:
  mail_from_address: ''
  address: ''
  port: ''
  domain: ''
  user_name: ''
  password: ''

